#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinAssetsApp.Droid.Resource", IsApplication=true)]

namespace XamarinAssetsApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int _3d_glasses = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int alarm_clock = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int block = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int book = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int brightness = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int brush = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int calendar = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int calendar_1 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int camera = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int charging = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int clock = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int compass = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int credit_card = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int delete = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int document = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int download = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int eye = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int flag = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int floppy_disk = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int folder = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int garbage = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int gift = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int heart = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int house = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Icon = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int key = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int loading = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int @lock = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int loupe = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int magic_wand = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int mail = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int map = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int message = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int notification = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int page = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int pen = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int pencil = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int picture = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int pie_chart = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int play_button = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int push_pin = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int security = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int send = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int settings = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int shopping_bag = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int shopping_basket = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int shopping_cart = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int video_player = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int vlc = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int voice_mail = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int wifi = 2130837554;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int myButton = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int myImage = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
